# Generated by Django 4.1.4 on 2023-01-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_rename_img_movie_imge'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='pic',
            field=models.ImageField(default=2, upload_to='pics'),
            preserve_default=False,
        ),
    ]
