# Generated by Django 4.1.4 on 2023-01-12 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_movie_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='pic',
        ),
    ]
