# Generated by Django 4.1.4 on 2023-01-12 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0005_remove_movie_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='imge',
            new_name='img',
        ),
    ]
