# Generated by Django 4.1.4 on 2023-01-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0006_rename_imge_movie_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='pic', upload_to='gallery'),
        ),
    ]
